version: "3.8"

networks:
  node:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
services:

  benchmarker:
    image: redislabs/memtier_benchmark:latest
    depends_on:
      - redis01
      - redis02
      - redis03
      - redis04
      - redis05
      - redis06
    networks:
      node:
        ipv4_address: 10.1.0.30
    command: sleep infinity
    entrypoint: ""

  cluster_init:
    image: redis:6
    depends_on:
      - redis01
      - redis02
      - redis03
      - redis04
      - redis05
      - redis06
    networks:
      node:
        ipv4_address: 10.1.0.2
    command: redis-cli --cluster create 10.1.0.11:7001 10.1.0.12:7002 10.1.0.13:7003 10.1.0.14:7004 10.1.0.15:7005 10.1.0.16:7006

  redis01:
    build: ./
    ports:
      - "7001:7001"
    environment:
      EXPOSE_PORT: 7001

    networks:
      node:
        ipv4_address: 10.1.0.11
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000


  redis02:
    build: ./
    ports:
      - "7002:7002"
    environment:
      EXPOSE_PORT: 7002
    networks:
      node:
        ipv4_address: 10.1.0.12
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  redis03:
    build: ./
    ports:
      - "7003:7003"
    environment:
      EXPOSE_PORT: 7003
    networks:
      node:
        ipv4_address: 10.1.0.13
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  redis04:
    build: ./
    ports:
      - "7004:7004"
    environment:
      EXPOSE_PORT: 7004
    networks:
      node:
        ipv4_address: 10.1.0.14
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  redis05:
    build: ./
    ports:
      - "7005:7005"
    environment:
      EXPOSE_PORT: 7005
    networks:
      node:
        ipv4_address: 10.1.0.15
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  redis06:
    build: ./
    ports:
      - "7006:7006"
    environment:
      EXPOSE_PORT: 7006
    networks:
      node:
        ipv4_address: 10.1.0.16
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
